name: Deploy to Hugging Face + Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Push to Hugging Face
        uses: huggingface/huggingface-cli-action@v0.1.1
        with:
          api-token: ${{ secrets.HF_TOKEN }}
          repo-type: space
          repo-name: AD2000X/semantic-rag-demo
